/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Object describing a media thumbnail.
 *
 */
class ThumbnailUrl {
  /**
   * Create a ThumbnailUrl.
   * @member {string} [url] URL pointing to an thumbnail to use for media
   * content.
   * @member {string} [alt] Alt text to display for screen readers on the
   * thumbnail image.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ThumbnailUrl
   *
   * @returns {object} metadata of ThumbnailUrl
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ThumbnailUrl',
      type: {
        name: 'Composite',
        className: 'ThumbnailUrl',
        modelProperties: {
          url: {
            required: false,
            serializedName: 'url',
            type: {
              name: 'String'
            }
          },
          alt: {
            required: false,
            serializedName: 'alt',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ThumbnailUrl;
