// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['CLIENT_ID'] = 'be5a8c67-75dd-424a-b7da-746141e11f7f';
  process.env['CLIENT_SECRET'] = 'poR3ZiMgA3JSUkFOcSjtUGp';
  process.env['USER_ID'] = 'U3Z9ZUDK5:T03CWQ0QB';
  process.env['BOT_ID'] = 'B21S8SG7J:T03CWQ0QB';
  process.env['HOST_URL'] = 'https://slack.botframework.com';
  process.env['AZURE_SUBSCRIPTION_ID'] = 'db1ab6f0-4769-4b27-930e-01e2ef9c123c';
};

exports.scopes = [];
